/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2023-12-25 18:04:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1697163774356L));
    _jspx_dependants.put("jar:file:/C:/_spring_/Final%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring231110/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/index.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("<title>메인 페이지</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"indexBody\">\n");
      out.write("\n");
      out.write("	<header>\n");
      out.write("		<div class=\"headerContainer\" id=\"headerContainer\">\n");
      out.write("			<div>\n");
      out.write("				<span class=\"ezenDesign1\">STYLE</span><span class=\"ezenDesign2\">MATE</span>\n");
      out.write("			</div>\n");
      out.write("			<ul class=\"boxContainer\">\n");
      out.write("				<a href=\"/member/login\">\n");
      out.write("					<li>What we create(login)</li>\n");
      out.write("				</a>\n");
      out.write("				<a href=\"/common/main\">\n");
      out.write("					<li>Careers(main)</li>\n");
      out.write("				</a>\n");
      out.write("				<a href=\"/customer/enter\">\n");
      out.write("					<li>Investment</li>\n");
      out.write("				</a>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Slider main container -->\n");
      out.write("	<div class=\"swiper\">\n");
      out.write("		<!-- Additional required wrapper -->\n");
      out.write("		<div class=\"swiper-wrapper\">\n");
      out.write("			<!-- Slides1 -->\n");
      out.write("			<div class=\"swiper-slide\">\n");
      out.write("				<a href=\"#\" class=\"slideP\"> <video autoplay loop muted\n");
      out.write("						preload=\"none\" class=\"video\">\n");
      out.write("						<source src=\"/resources/movie/indexMovie.mp4\" type=\"video/mp4\">\n");
      out.write("					</video>\n");
      out.write("					<div class=\"text\">\n");
      out.write("						<p id=\"mainText\">\n");
      out.write("							<strong>IMAGINE </strong><span>YOUR DREAM.</span><span> WE\n");
      out.write("								CREATE</span><strong> REALITY</strong>\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("				</a>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div id=\"backgroundImg1\">\n");
      out.write("		<div class=\"secText\" id=\"secText\">\n");
      out.write("			<h3>Company</h3>\n");
      out.write("			<p>\n");
      out.write("				<strong>고객의 꿈, </strong> <span>그리고 </span> <span><strong>맞춤공간</strong>을</span><br>\n");
      out.write("				<span>실현하기 위해 </span> <strong>열정</strong> <span>을 다합니다.</span>\n");
      out.write("			</p>\n");
      out.write("			<p>\n");
      out.write("				스타일메이트는 고객의 꿈을 이루어 드릴 수 있는<br> 준비된 공간전문가 집단입니다.\n");
      out.write("			</p>\n");
      out.write("\n");
      out.write("			<a href=\"/common/main\"><span>STYLE MATE</span><img\n");
      out.write("				src=\"/resources/img/arrow.png\">\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"/resources/js/index.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
