/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2023-12-25 18:20:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chatfolder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class box_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1697163774356L));
    _jspx_dependants.put("jar:file:/C:/_spring_/Final%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring231110/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("/* 채팅 관련 스타일 */\n");
      out.write(".media {\n");
      out.write("	padding: 10px;\n");
      out.write("	border-bottom: 1px solid #eee;\n");
      out.write("	height: 70px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".media img {\n");
      out.write("	border-radius: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".media-heading {\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".subject {\n");
      out.write("	display: flex; /* Flexbox를 사용하여 아이템들을 가로로 배열 */\n");
      out.write("	justify-content: space-between; /* 아이템들 사이에 공간을 균등하게 분배 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".find-link {\n");
      out.write("	margin-left: 20px; /* 원하는 간격을 설정 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("img {\n");
      out.write("	vertical-align: baseline !important;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<title>실시간 채팅 메신저 서비스</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/resources/css/main.css\"> -->\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=82r632girq\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("	\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0\" />\n");
      out.write("<link href=\"../resources/css/box.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"mainBody\">\n");
      out.write("\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("	<!-- <div class=\"snow-wrap\"> -->\n");
      out.write("	<!-- 	<div> -->\n");
      out.write("	<!-- 	</div> -->\n");
      out.write("	<!-- </div> -->\n");
      out.write("\n");
      out.write("	<div class=\"total\">\n");
      out.write("		<div class=\"snow-wrap\"></div>\n");
      out.write("		<!-- <div class=\"subject\">채팅페이지</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"content\">\n");
      out.write(" <div class=\"morebigmesbox\">\n");
      out.write("			<div class=\"collapse navbar-collapse\"\n");
      out.write("				id=\"bs-example-navbar-collapse-1\">\n");
      out.write("				<ul class=\"nav navbar-nav\">\n");
      out.write("					<!--    		<li><a href=\"/chaturl/chat\">채팅메신저페이지</a> </li> -->\n");
      out.write("					<!-- 231212주석처리 -->\n");
      out.write("					<!-- 	    <li><a href=\"/member/index\">메인</a></li> -->\n");
      out.write("					<!-- 231212주석처리 -->\n");
      out.write("					<!-- 	    <li><a href=\"/chaturl/find\" class=\"find-link\">사원찾기</a></li>-->\n");
      out.write("					<!--컨트롤러가 잡게 함 -->\n");
      out.write("<!-- 					<li class=\"active\"> -->\n");
      out.write("<!-- 						<a class=\"amessageboxbtn\" ref=\"/chaturl/box\">메시지함<span id=\"unread\"class=\"label label-info\"></span></a> -->\n");
      out.write("<!-- 					</li> -->\n");
      out.write("					<!-- 컨트롤러가 잡게 함 -->\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- 231111_1전경환 채팅창관련해서 뭐 넣기 S ------------------------------------->\n");
      out.write("           <div>\n");
      out.write("            <div>\n");
      out.write("                <div class=\"portlet-heading\">\n");
      out.write("                	<div class=\"portlet-title\">\n");
      out.write("                    </div>	\n");
      out.write("                	<div class=\"clearfix\"></div>\n");
      out.write("            	</div>\n");
      out.write("	            <div id=\"chat\" >\n");
      out.write("	                <div id=\"chatList\" style=\"overflow-y: auto; overflow-x: hidden; width: auto; height:711px;\"> <!-- portlet-body chat widget -->\n");
      out.write("			\n");
      out.write("							    <div class=\"container\">\n");
      out.write("									<table class=\"\" style=\"margin: 0 auto\">\n");
      out.write("										<thead>\n");
      out.write("											<tr>\n");
      out.write("												<th style=\"display: flex;\">\n");
      out.write("													<div><h2 style=\"color: white; margin-top:0px;\">채팅 목록 </h4></div>\n");
      out.write("													<div><span id=\"unread\"class=\"label label-info\"></span></div>\n");
      out.write("												</th> \n");
      out.write("											</tr>\n");
      out.write("										</thead>\n");
      out.write("\n");
      out.write("										<div style=\"overflow-y: auto; width: 100%; max-height: 450px;\">										    \n");
      out.write("										    <table class=\"table table-hover\" style=\"text-align: center;  margin: 0 auto;\">										       \n");
      out.write("										       <tbody id=\"boxTable\" class=\"myTable\">	\n");
      out.write("											        	<tr onclick=\"location.href='chat2.jsp?toID=<some_id>'\">\n");
      out.write("<!-- 											        		<td style=\"\"> -->\n");
      out.write("<!-- 											                    <h5>Test0</h5>									                     -->\n");
      out.write("<!-- 											                </td> -->\n");
      out.write("											                <td style=\"width: 150px;\">\n");
      out.write("											                    <h5>Test1</h5>\n");
      out.write("											                </td>\n");
      out.write("											                <td>\n");
      out.write("											                    <h5>Test2</h5>									                    \n");
      out.write("											                </td>										                  \n");
      out.write("											                <td>\n");
      out.write("											                    <div class=\"pull-right\">Test3</div>\n");
      out.write("											                </td>\n");
      out.write("											            </tr>										        											      \n");
      out.write("										        </tbody>									        \n");
      out.write("										    </table>										    \n");
      out.write("										</div>\n");
      out.write("										<div id=\"unreadContainer\">\n");
      out.write("										</div>\n");
      out.write("									</table>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("	                </div>\n");
      out.write("	                <div>    \n");
      out.write("	                    <div>\n");
      out.write("	                        <div style=\"display: none;\">\n");
      out.write("	                            <input style=\"height: 40px; width: 20%;\" type=\"text\" id=\"chatName\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  maxlength=\"8\" readonly=\"readonly\">\n");
      out.write("	                        </div>\n");
      out.write("	                    </div>\n");
      out.write("						<div style=\"height: 80px; display: flex; align-items: center;\">\n");
      out.write("\n");
      out.write("						    <div>\n");
      out.write("						        <button id=\"chatSubmitBtn\" type=\"button\" class=\"btn btn-default\" >전송</button>\n");
      out.write("						    </div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("           </div>\n");
      out.write("        </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("     \n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("			\n");
      out.write("			\n");
      out.write("<!-- 			<div class=\"morebigmesbox\"> -->\n");
      out.write("<!-- 				<div class=\"bigmesbox\"> -->\n");
      out.write("<!-- 					<div class=\"smallmesbox\"> -->\n");
      out.write("<!-- 						<div > -->\n");
      out.write("<!-- 						<span class=\"material-symbols-outlined\" id = \"icon1\"> -->\n");
      out.write("<!-- 						person -->\n");
      out.write("<!-- 						</span> -->\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 						<div> -->\n");
      out.write("<!-- 							<div class=\"moresmallbox\"> -->\n");
      out.write("<!-- 								<div>테스트사용자1</div> -->\n");
      out.write("<!-- 								<div>알람</div> -->\n");
      out.write("<!-- 							<div  class=\"moresmallbox2\"> -->\n");
      out.write("<!-- 							<div class=\"conten\"> -->\n");
      out.write("<!-- 								내용1내용2내용3내용4내용5내용6내용7내용8내용9내용10내용11내용12내용13123456789123456789123456789 -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 						<div class=\"day\">날짜</div> -->\n");
      out.write("<!-- 					</div> -->\n");
      out.write("<!-- 										<div class=\"smallmesbox\"> -->\n");
      out.write("<!-- 						<div > -->\n");
      out.write("<!-- 						<span class=\"material-symbols-outlined\" id = \"icon1\"> -->\n");
      out.write("<!-- 						person -->\n");
      out.write("<!-- 						</span> -->\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 						<div> -->\n");
      out.write("<!-- 							<div class=\"moresmallbox\"> -->\n");
      out.write("<!-- 								<div>testuser1</div> -->\n");
      out.write("<!-- 								<div>알람</div> -->\n");
      out.write("<!-- 							</div  class=\"moresmallbox2\"> -->\n");
      out.write("<!-- 							<div class=\"conten\"> -->\n");
      out.write("<!-- 								내용1 -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 						<div class=\"day\">2023-12-19 오전 09:15</div> -->\n");
      out.write("<!-- 					</div> -->\n");
      out.write("<!-- 				</div> -->\n");
      out.write("<!-- 			</div> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- 231111_1전경환 채팅창관련해서 뭐 넣기 E ------------------------------------->\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/box.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		// 문서가 준비되면 실행될 함수를 정의합니다.\n");
      out.write("		function setup() {\n");
      out.write("			// input 필드에 keypress 이벤트 리스너를 추가합니다.\n");
      out.write("			document.getElementById('chatContent').addEventListener('keypress',\n");
      out.write("					function(e) {\n");
      out.write("						// 엔터 키의 키 코드는 13입니다.\n");
      out.write("						if (e.keyCode === 13) {\n");
      out.write("							// 엔터 키가 눌렸다면, chatSubmitBtn의 클릭 이벤트를 트리거합니다.\n");
      out.write("							document.getElementById('chatSubmitBtn').click();\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		// 페이지 로딩 후 setup 함수를 호출합니다.\n");
      out.write("		window.onload = setup;\n");
      out.write("\n");
      out.write("		chatSubmitBtn.style.display = \"none\";\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/chatfolder/box.jsp(50,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("../resources/bootstrap337/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/chatfolder/box.jsp(76,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/index_all.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
