/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2023-12-25 18:20:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chatfolder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1697163774356L));
    _jspx_dependants.put("jar:file:/C:/_spring_/Final%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring231110/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("  \n");
      out.write("  \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("    <title>실시간 채팅 메신저 서비스</title>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("	<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" 	type=\"text/css\">\n");
      out.write("	<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" 	type=\"text/css\">\n");
      out.write("<!-- 	<link rel=\"stylesheet\" type=\"text/css\" href=\"경로/chat2.css\"> -->\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/resources/css/main.css\"> -->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("<div class=\"total\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <div class=\"navBorder\"></div>\n");
      out.write(" \n");
      out.write("   <div class=\"header-container\">\n");
      out.write("   	<h1 class=\"title\"> 채팅 상대방 :  ");
      out.print( request.getParameter("toID") );
      out.write("</h1>\n");
      out.write("   	              \n");
      out.write("                \n");
      out.write("                       \n");
      out.write("                \n");
      out.write("            \n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("	    <ul class=\"nav navbar-nav\">\n");
      out.write("	        <li>\n");
      out.write("	            <a href=\"/chaturl/box\" class=\"message-box-link\">\n");
      out.write("	                메시지함\n");
      out.write("	                <span id=\"unread\" class=\"label label-info\"></span>\n");
      out.write("	                <i class=\"fas fa-envelope\"></i> <!-- Font Awesome envelope icon -->\n");
      out.write("	            </a>\n");
      out.write("	        </li>\n");
      out.write("\n");
      out.write("	    </ul>\n");
      out.write("	</div>\n");
      out.write("   	</div>\n");
      out.write("   <div class=\"border\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id = \"chattotal\">\n");
      out.write("<!-- 231111_1전경환 채팅창관련해서 뭐 넣기 S -------------------------------------> <!-- class=\"content\" -->\n");
      out.write("<!-- https://www.youtube.com/watch?v=8s98IhtgwZ0&list=PLRx0vPvlEmdAlUbX_TGDxaSxKCvfl2isa&index=6 -->\n");
      out.write("<div >\n");
      out.write("    <div >\n");
      out.write("        <div >\n");
      out.write("            <div >\n");
      out.write("                <div class=\"portlet-heading\">\n");
      out.write("                	<div class=\"portlet-title\">\n");
      out.write("<!--                     	<h4><i class=\"fa fa-circle text-green\"></i>실시간 채팅창</h4> -->\n");
      out.write("                    </div>	\n");
      out.write("                	<div class=\"clearfix\"></div>\n");
      out.write("            	</div>\n");
      out.write("	            <div id=\"chat\" >\n");
      out.write("	                <div id=\"chatList2\" style=\"\"> <!-- portlet-body chat widget -->\n");
      out.write("	                <!--------------- 여기에 뭔가 주루루륵 반복해서 들어가는 부분 같음 S------------------------------------------------------------------->\n");
      out.write("					<div style=\"margin:20px;\">채팅 시작 전입니다.</div>\n");
      out.write("<!-- 					<div class=\"row\"> -->\n");
      out.write("<!-- 						<div class=\"col-lg-12\"> -->\n");
      out.write("<!-- 							<div class=\"media\"> -->\n");
      out.write("<!-- 								<a class=\"pull-left\" href=\"#\"> -->\n");
      out.write("<!-- 									<img class=\"media-object img-circle\" style=\"width: 30px; height:30px;\" src=\"/resources/img/anoyicon.png\" alt=\"\"> -->\n");
      out.write("<!-- 								</a> -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("<!-- 							<div class=\"media-body\"> -->\n");
      out.write("<!-- 								<h4 class=\"media-heading\"> -->\n");
      out.write("<!-- 									chatName<span class=\"small pull-rigth\">chatTime </span> -->\n");
      out.write("<!-- 								</h4> -->\n");
      out.write("<!-- 								<p>chatContent</p> -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("							\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 					</div> -->\n");
      out.write("					\n");
      out.write("<!-- 					<div class=\"row\"> -->\n");
      out.write("<!-- 						<div class=\"col-lg-12\"> -->\n");
      out.write("<!-- 							<div class=\"media\"> -->\n");
      out.write("<!-- 								<a class=\"pull-left\" href=\"#\"> -->\n");
      out.write("<!-- 									<img class=\"media-object img-circle\" style=\"width: 30px; height:30px;\" src=\"/resources/img/anoyicon.png\" alt=\"\"> -->\n");
      out.write("<!-- 								</a> -->\n");
      out.write("<!-- 							<div class=\"media-body\"> -->\n");
      out.write("<!-- 								<h4 class=\"media-heading\"> -->\n");
      out.write("<!-- 									chatName<span class=\"small pull-rigth\"; style=\"margin-left: 10px;\">     chatTime </span> -->\n");
      out.write("<!-- 								</h4> -->\n");
      out.write("<!-- 								<p>chatContent</p> -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("<!-- 							</div> -->\n");
      out.write("<!-- 						</div> -->\n");
      out.write("<!-- 					</div> -->\n");
      out.write("	                <!--------------- 여기에 뭔가 주루루륵 반복해서 들어가는 부분 같음 E------------------------------------------------------------------->\n");
      out.write("	                </div>\n");
      out.write("	                <div id=\"messageinputboxbigdiv\">    \n");
      out.write("	                    <div>\n");
      out.write("	                        <div>\n");
      out.write("\n");
      out.write("\n");
      out.write("								<!-- jgh231213 채팅자 이름 안보이게 처리 -->\n");
      out.write("	                            <input style=\"height: 30px; width: 20%;\" type=\"text\" id=\"chatName\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  maxlength=\"8\" readonly=\"readonly\">\n");
      out.write("	                        </div>\n");
      out.write("	                    </div>\n");
      out.write("						<div id = \"messageinputbox1\" style=\"\">\n");
      out.write("						    <div style=\"flex:0.97;\">\n");
      out.write("						    	\n");
      out.write("						        <textarea id=\"chatContent\" style=\"\"  class=\"form-control\" placeholder=\"메시지를 입력하세요\" maxlength=\"100\"></textarea>\n");
      out.write("						    	\n");
      out.write("						    </div>\n");
      out.write("						    <div>\n");
      out.write("						        <button id=\"chatSubmitBtn\" type=\"button\" class=\"btn btn-default\" >전송</button>\n");
      out.write("						    </div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("           </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"alert alert-success\" id=\"successMessage\" style=\"display: none;\">\n");
      out.write("	<strong>메세지 전송에 성공했습니다.</strong>\n");
      out.write("</div>\n");
      out.write("<div class=\"alert alert-danger\" id=\"dangerMessage\" style=\"display: none;\">\n");
      out.write("	<strong>이름과 내용을 모두 입력하세요</strong>\n");
      out.write("</div>\n");
      out.write("<div class=\"alert alert-warning\" id=\"warningMessage\" style=\"display: none;\">\n");
      out.write("	<strong>데이터베이스 오류 발생</strong>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 231111_1전경환 채팅창관련해서 뭐 넣기 E ------------------------------------->\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/chat2.js\"></script>\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/resources/js/chat.js\"></script> -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	printChatList();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("		 // 문서가 준비되면 실행될 함수를 정의합니다.\n");
      out.write("		    function setup() {\n");
      out.write("		        // input 필드에 keydown 이벤트 리스너를 추가합니다.\n");
      out.write("		        document.getElementById('chatContent').addEventListener('keydown', function(e) {\n");
      out.write("		            // 엔터 키의 키 코드는 13입니다.\n");
      out.write("		            if (e.keyCode === 13 && !e.shiftKey) {\n");
      out.write("		                // 엔터 키가 눌렸고 Shift 키가 눌리지 않았다면, chatSubmitBtn의 클릭 이벤트를 트리거합니다.\n");
      out.write("		                document.getElementById('chatSubmitBtn').click();\n");
      out.write("		                // 기본 동작을 막습니다 (새 줄 입력 방지)\n");
      out.write("		                e.preventDefault();\n");
      out.write("		            }\n");
      out.write("		        });\n");
      out.write("		    }\n");
      out.write("		\n");
      out.write("		    // 페이지 로딩 후 setup 함수를 호출합니다.\n");
      out.write("		    window.onload = setup;\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/chatfolder/chat2.jsp(23,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/index_all.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/chatfolder/chat2.jsp(24,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("../resources/css/chat2.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
